# Generated by Django 4.2.2 on 2023-06-25 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Outside', 'Outside Valley')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='location/')),
                ('price', models.TextField()),
                ('guide', models.CharField(max_length=20)),
                ('g_phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('language', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=100)),
                ('people', models.IntegerField()),
                ('sdate', models.DateField(default=datetime.date.today)),
                ('edate', models.DateField(default=datetime.date.today)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.guide')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.add_location')),
            ],
        ),
    ]
