# Generated by Django 4.2.2 on 2023-06-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_location',
            name='g_phone',
        ),
        migrations.RemoveField(
            model_name='add_location',
            name='guide',
        ),
    ]
