# Generated by Django 4.2.2 on 2023-06-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_add_location_g_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_location',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.guide'),
        ),
    ]
