# Generated by Django 4.2.2 on 2023-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_book_location_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_location',
            name='guide',
            field=models.CharField(max_length=50),
        ),
    ]
