# Generated by Django 4.2.2 on 2023-06-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_book_location_guide_alter_book_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_location',
            old_name='edate',
            new_name='EndingDate',
        ),
        migrations.RenameField(
            model_name='book_location',
            old_name='pname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='book_location',
            old_name='people',
            new_name='People',
        ),
        migrations.RenameField(
            model_name='book_location',
            old_name='sdate',
            new_name='StartingDate',
        ),
    ]
